apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: abugarciapro/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - containerPort: 3111
          protocol: TCP
        livenessProbe:
          httpGet:
            host:
            scheme: HTTP
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            host:
            scheme: HTTP
            path: /healthz
            port: 3111
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi